<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZfSnapUrl\Module'        => __DIR__ . '/Module.php',
    'ZfSnapUrl\Routable'      => __DIR__ . '/src/ZfSnapUrl/Routable.php',
    'ZfSnapUrl\View\Helper\U' => __DIR__ . '/src/ZfSnapUrl/View/Helper/U.php',
);
